name: linting
on: [pull_request]
jobs:
  lint-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Run ESLint
        run: npx eslint .
      - name: Run Prettier
        run: npx prettier --check .
